sfeed_update: don't preserve permissions of tmp files by moving, so copy
noticed on DragonFlyBSD where it prints a warning when moving the file from
/tmp.

To reproduce it:

	touch /tmp/file
	mv /tmp/file ~/

On other systems this would not print a warning, but it would preserve the
group permissions etc.

diff --git a/sfeed_update b/sfeed_update
--- a/sfeed_update
+++ b/sfeed_update
@@ -143,11 +143,12 @@ feed() {
 	fi
 	rm -f "${tmpfeedfile}.merge"
 
-	# atomic move.
-	if ! mv "${tmpfeedfile}.order" "${sfeedfile}"; then
-		log "${name}" "FAIL (MOVE)"
+	# copy
+	if ! cp "${tmpfeedfile}.order" "${sfeedfile}"; then
+		log "${name}" "FAIL (COPY)"
 		return
 	fi
+	rm -f "${tmpfeedfile}.order"
 
 	# OK
 	log "${name}" "OK"
